on:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          ls -ld ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

      - name: set permissions for ssh key
        run: |
          chmod 600 ~/.ssh/id_ed25519

      - name: add ssh host to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: connect and output message
        run: |
          ssh -T -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
             pkill -f "dotnet run"
             rm -rf ~/back/*
             rm -rf ~/.ssh/id_ed25519
             echo "${{ secrets.SSH_VPS_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
             chmod 700 ~/.ssh/id_ed25519
             mkdir -p ~/back
             cd ~/back/
             git clone git@github.com:MichaelPopovCa/translator-ba.git
             cd translator-ba/QuickTranslate
             sed -i 's/API_KEY_VENDOR_ONE/${{ secrets.API_KEY_VENDOR_ONE }}/g' appsettings.json
             sed -i 's/API_VENDOR_ONE/${{ secrets.API_VENDOR_ONE }}/g' appsettings.json
             dotnet restore
             nohup dotnet run --project QuickTranslate.csproj &
             sleep 5
             exit
          EOF
