on:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          ls -ld ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

      - name: set permissions for ssh key
        run: |
          chmod 600 ~/.ssh/id_ed25519

      - name: add ssh host to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: connect and output message
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
             rm -rf ~/.ssh/id_ed25519
             echo "${{ secrets.SSH_VPS_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
             chmod 700 ~/.ssh/id_ed25519
             cd ~/back/
             git clone git@github.com:MichaelPopovCa/mikhailpopov-ba.git
             cd mikhailpopov-ba/
             cd mikhailpopov-ba/
             mvn clean install
             mvn spring-boot:run
          EOF
